# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 19:29
from __future__ import unicode_literals

import contentmanager.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('slug', models.SlugField(unique=True)),
                ('bio', models.TextField(verbose_name='Короткая справка')),
                ('avatar', models.ImageField(upload_to='authors/', verbose_name='Аватар')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Почта')),
                ('is_winner', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Elder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('bio', models.TextField(verbose_name='Короткая справка')),
                ('avatar', models.ImageField(upload_to='elders/', verbose_name='Аватар')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Почта')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('top_image', models.ImageField(upload_to=contentmanager.models.upload_location)),
                ('content', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('top_image', models.ImageField(upload_to=contentmanager.models.upload_location)),
                ('content', models.TextField()),
                ('publish', models.DateTimeField()),
                ('update', models.DateTimeField(auto_now=True, verbose_name='время создания')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='обновлён')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentmanager.Author', verbose_name='Автор')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
