# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 20:13
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
