# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 20:20
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanager', '0002_auto_20171217_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
